#!/bin/sh

# Check if the last commit message contains "[skip changelog]"
if git log -1 --pretty=%B | grep -q "\[skip changelog\]"; then
  exit 0
fi

# Run standard-version
npm run release -- --no-verify

# Commit the changelog update with a skip message
git add CHANGELOG.md package.json package-lock.json
git commit -m "chore: update changelog [skip changelog]"
